{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
        {{- include "relay-balancer.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
  podMetricsEndpoints:
    - interval: 30s
      path: /metrics
      port: dashboard
{{- end }}
