apiVersion: v1
kind: Service
metadata:
  name: {{ include "relay-balancer.fullname" . }}
  labels:
    {{- include "relay-balancer.labels" . | nindent 8 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.env.portname }}
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "relay-balancer.labels" . | nindent 8 }}
    {{- with .Values.podLabels }}
    {{- toYaml . | nindent 8 }}
    {{- end }}
